# Generated by Django 3.2.23 on 2024-01-25 22:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBooking',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_on', models.DateField(auto_now=True)),
                ('created_on', models.DateField(auto_now=True)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField(default=datetime.time(8, 0))),
                ('event_choice', models.CharField(choices=[('Personal Trainer', 'Personal Trainer'), ('Dietist', 'Dietist'), ('Rehab', 'Rehab'), ('Massage', 'Massage')], max_length=30)),
                ('booking_status', models.CharField(choices=[(0, 'Awaiting Approval'), (1, 'Confirmed')], max_length=30)),
                ('extra_comments', models.TextField(blank=True, null=True, verbose_name='Anything we should know?')),
                ('options_field', models.CharField(choices=[('option_yes', 'Yes🤩'), ('option_no', 'No')], default='option_yes', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_booking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
    ]
