# Generated by Django 3.2.23 on 2024-01-15 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBooking',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_on', models.DateField(auto_now=True)),
                ('created_on', models.DateField(auto_now=True)),
                ('event_date', models.DateField()),
                ('lesson_time', models.TimeField(default='08:00')),
                ('event_choice', models.CharField(choices=[('Personal Trainer', 'Personal Trainer'), ('Dietist', 'Dietist'), ('Rehab', 'Rehab'), ('Massage', 'Massage')], max_length=30)),
                ('booking_status', models.IntegerField(choices=[(0, 'Awaiting Approval'), (1, 'Confirmed')], default=0)),
                ('extra_comments', models.TextField(null=True)),
                ('option_yes', models.BooleanField(default=False, verbose_name='This is my first appointment!🤩')),
                ('option_no', models.BooleanField(default=False, verbose_name="I'm a recurring member!😄")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_booking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
    ]
