# Generated by Django 3.2.23 on 2024-01-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventbooking',
            name='option_no',
        ),
        migrations.RemoveField(
            model_name='eventbooking',
            name='option_yes',
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='options_field',
            field=models.CharField(choices=[('option_yes', 'Yes'), ('option_no', 'No')], default='option_yes', max_length=10),
        ),
    ]
