# Generated by Django 3.2.23 on 2023-12-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbooking',
            name='lesson_time',
            field=models.TimeField(choices=[('07:30', '07:30'), ('08:00', '08:00')], default='08:00'),
        ),
    ]
