# Generated by Django 3.2.23 on 2024-01-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20240115_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('membership_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('memberlevel', models.CharField(choices=[('Brons', 'Brons'), ('Silver', 'Silver'), ('Gold', 'Gold')], default='Brons', max_length=80)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='extra_comments',
            field=models.TextField(null=True, verbose_name='Anything you would like to add?'),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='options_field',
            field=models.CharField(choices=[('option_yes', 'Yes🤩'), ('option_no', 'No')], default='option_yes', max_length=10),
        ),
    ]
