# Generated by Django 3.2.23 on 2023-12-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_eventbooking_lesson_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbooking',
            name='lesson_time',
            field=models.TimeField(choices=[('07:30', '07:30'), ('20:00', '20:00')], default='08:00'),
        ),
    ]
