# Generated by Django 3.2.23 on 2024-01-19 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_eventbooking_lesson_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbooking',
            name='lesson_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
