# Generated by Django 3.2.23 on 2024-01-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_eventbooking_lesson_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbooking',
            name='extra_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Anything you would like to add?'),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='lesson_time',
            field=models.TimeField(),
        ),
    ]
