# Generated by Django 3.2.23 on 2024-01-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_alter_eventbooking_lesson_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbooking',
            name='lesson_time',
            field=models.CharField(choices=[('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00')], max_length=10),
        ),
    ]
