# Generated by Django 3.2.23 on 2024-01-20 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_alter_eventbooking_lesson_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbooking',
            name='start_time',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
    ]
