# Generated by Django 3.2.23 on 2024-01-20 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_eventbooking_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventbooking',
            name='lesson_time',
        ),
    ]
