# Generated by Django 3.2.23 on 2024-01-20 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_remove_eventbooking_lesson_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbooking',
            name='start_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
